import {Renderer} from './runtime/viewer/js/renderer.js';
import {Camera} from './runtime/viewer/js/camera.js';
import {initWasm, loadModelFromUrl, sortSplats, freeSplatSh} from './runtime/viewer/js/wasm.js';
import {reproject, samePose} from './projection.mjs';
const $=id=>document.getElementById(id);
const json=async url=>{const r=await fetch(url);if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json();};
let renderer,camera,sidecar,scene,bundle,records=[],current,referencePixels,maskPixels;
const opts={primitive:0,gamut:[1,0,0,0,1,0,0,0,1],transfer:0,isLinear:false,shDegree:3,exposure:1,opacityScale:1,upAxis:'z',showGrid:false,background:[0,0,0]};
function render(){const f=camera.forward(),p=camera.pos;renderer.updateSplatOrder(sortSplats(0,...p,...f));renderer.render(camera,opts);}
function viewpoint(){return {cameraId:current.id,position:[...camera.pos],forward:camera.forward(),up:camera.up(),projection:sidecar.projection};}
function samePosition(){return samePose(viewpoint(),current);}
function reference(){if(!referencePixels)return;const p=sidecar.projection,ctx=$('reference').getContext('2d');const pixels=new Uint8ClampedArray(referencePixels);if($('overlay').checked)for(let i=0;i<pixels.length;i+=4)if(maskPixels[i]===0){pixels[i]=Math.round(pixels[i]*.5+127);pixels[i+1]*=.5;pixels[i+2]*=.5;}
ctx.putImageData(new ImageData(pixels,p.width,p.height),0,0);$('reference-label').textContent=samePosition()?'同じ位置・向き・透視投影に変換した元画像（学習入力）':'参考画像：元の撮影位置・向き。現在の視点の正解画像ではありません';}
async function pixels(url){const im=new Image();im.src=url;await im.decode();const cv=document.createElement('canvas');cv.width=im.naturalWidth;cv.height=im.naturalHeight;const ctx=cv.getContext('2d');ctx.drawImage(im,0,0);return ctx.getImageData(0,0,cv.width,cv.height);}
let selection=0;
async function select(id){const generation=++selection;current=sidecar.views.find(v=>v.id===Number(id));$('capture').value=String(current.id);camera.lookAt(current.position,current.position.map((v,i)=>v+current.forward[i]),current.up);render();$('original').href=current.imageUrl;$('mask').href=current.maskUrl;referencePixels=null;$('reference').getContext('2d').clearRect(0,0,$('reference').width,$('reference').height);$('reference-label').textContent='対応する元画像を読み込んでいます…';const selected=current;const [im,mask]=await Promise.all([pixels(selected.imageUrl),pixels(selected.maskUrl)]);if(generation!==selection)return;referencePixels=reproject(im,selected.intrinsics,sidecar.projection);maskPixels=reproject(mask,selected.intrinsics,sidecar.projection,true);reference();}
function safely(fn){return async(...args)=>{try{await fn(...args);}catch(e){$('status').textContent='エラー: '+e.message;}};}
async function boot(){[scene,sidecar,bundle]=await Promise.all([json('scene.json'),json('cameras.json'),json('bundle.json')]);const {width,height,fovDegrees}=sidecar.projection;for(const id of ['model','reference']){$(id).width=width;$(id).height=height;}
await initWasm();renderer=new Renderer($('model'));camera=new Camera();camera.fov=fovDegrees*Math.PI/180;camera.model='perspective';const model=await loadModelFromUrl('model.ply','model.ply');if(model.kind!=='splat')throw new Error('Gaussian PLY is required');if(renderer.setSplat(model.data)==='oom-sh')throw new Error('GPU memory不足。表示条件を自動変更せず停止しました。');opts.shDegree=model.data.shDegree;if(opts.shDegree!==scene.renderer.shDegree)throw new Error('SH degree differs from model metadata');freeSplatSh();
for(const v of sidecar.views){const o=document.createElement('option');o.value=v.id;o.textContent=`${v.source.captureId||'single'} / ${v.source.cameraId} / frame ${v.source.frameIndex}`;$('capture').append(o);}
await select(sidecar.views[0].id);$('status').textContent=`描画完了 · ${model.data.count.toLocaleString()} Gaussian · 画質は視点別記録を参照（未記録は NOT_TESTED）`;
$('metadata').textContent=JSON.stringify({modelSha256:scene.modelSha256,cameraSha256:scene.cameraSha256,renderer:scene.renderer,shDegree:opts.shDegree,projection:sidecar.projection,units:sidecar.units,coordinateTransform:sidecar.worldFromReconstruction},null,2);
for(const id of ['capture','home','left','right','forward','back','look-left','look-right','look-up','look-down','save'])$(id).disabled=false;
$('capture').onchange=safely(()=>select($('capture').value));$('home').onclick=safely(()=>select(sidecar.views[0].id));$('overlay').onchange=reference;
for(const [id,axis,sign] of [['left','right',-1],['right','right',1],['forward','forward',1],['back','forward',-1]])$(id).onclick=safely(()=>{const step=Number($('step').value);if(!Number.isFinite(step)||step<=0||step>100)throw new Error('移動量を確認してください');const d=camera[axis]();camera.pos=camera.pos.map((v,i)=>v+d[i]*step*sign);render();reference();});
for (const [id,axis,sign] of [['look-left','right',-1],['look-right','right',1],['look-up','up',1],['look-down','up',-1]]) $(id).onclick=safely(()=>{const a=Math.PI/12,f=camera.forward(),d=camera[axis](),up=camera.up();const next=f.map((v,i)=>v*Math.cos(a)+d[i]*Math.sin(a)*sign);const nextUp=axis==='up'?up.map((v,i)=>v*Math.cos(a)-f[i]*Math.sin(a)*sign):up;camera.lookAt(camera.pos,camera.pos.map((v,i)=>v+next[i]),nextUp);render();reference();});
$('save').onclick=safely(()=>{for(const id of ['label','purpose','reviewer','reason'])if(!$(id).value.trim())throw new Error('確認箇所・用途・確認者・理由を入力してください');render();const record={schemaVersion:1,bundleId:bundle.id,category:'visual',status:$('result').value,label:$('label').value,purpose:$('purpose').value,reviewer:$('reviewer').value,reason:$('reason').value,at:new Date().toISOString(),device:navigator.userAgent,view:viewpoint(),shDegree:opts.shDegree,screenshot:$('model').toDataURL('image/png')};const text=JSON.stringify(record),a=$('download');if(a.href.startsWith('blob:'))URL.revokeObjectURL(a.href);a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=`fs-review-${Date.now()}.json`;a.hidden=false;$('export-json').value=text;$('save-message').textContent='保存用JSONを作成しました。下のリンクから保存し、python -m fs_capture preview-import PREVIEW 保存したJSON を実行してください。ブラウザによる保存完了はこの画面では判定しません。';});
records=(await json('qa.json')).items;for(const [i,r]of records.entries()){const o=document.createElement('option');o.value=i;o.textContent=`${r.status} · ${r.label} · ${r.reviewer}`;$('saved').append(o);}$('restore').disabled=!records.length;$('review-summary').textContent=`確認記録 ${records.length}件。判定は記録した用途・視点に限ります。移動範囲・公開情報・納品は NOT_TESTED。`;
$('restore').onclick=safely(async()=>{if($('saved').value==='')return;const r=records[Number($('saved').value)];await select(r.view.cameraId);camera.lookAt(r.view.position,r.view.position.map((v,i)=>v+r.view.forward[i]),r.view.up);render();reference();$('label').value=r.label;$('purpose').value=r.purpose;$('reviewer').value=r.reviewer;$('reason').value=r.reason;$('result').value=r.status;});}
safely(boot)();
